services:
  # ===== BASE DE DATOS =====
  user-db:
    image: postgres:13-alpine
    container_name: user_postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
    ports:
      - "5432:5432"
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    networks:
      - auth_user_network

  # ===== AUTH SERVICE =====
  auth-service:
    build: ./auth-service
    container_name: auth_service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      USER_SERVICE_URL: http://user-service:8081
    networks:
      - auth_user_network
    depends_on:
      - user-service

  # ===== USER SERVICE =====
  user-service:
    build: ./user-service
    container_name: user_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_admin
      SPRING_DATASOURCE_PASSWORD: user_password
    networks:
      - auth_user_network
    depends_on:
      - user-db

volumes:
  user_pg_data:

networks:
  auth_user_network:
    driver: bridge