server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://user-db:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:user_admin}
    password: ${SPRING_DATASOURCE_PASSWORD:user_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
